
import React, { useState } from 'react';
import { analyzeFinancials } from '../services/geminiService';
import { FinancialReport } from '../types';
import { PieChart, TrendingUp, DollarSign, Award, ArrowRight, Zap, Loader2, MapPin, FileText, CheckCircle2, UploadCloud, Printer } from 'lucide-react';

const Financials: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'profit' | 'invoicing'>('profit');
  const [report, setReport] = useState<FinancialReport | null>(null);
  const [loading, setLoading] = useState(false);
  
  // Invoicing State
  const [invoices, setInvoices] = useState([
      { id: 1, client: "Logística Sur SpA", route: "Stgo - Valpo", amount: 450000, status: "Pending", dte: null },
      { id: 2, client: "Constructora Andina", route: "Puerto Montt - Osorno", amount: 180000, status: "DTE Generated", dte: "F-3392" },
      { id: 3, client: "Retail Chile Ltd", route: "Antofagasta - Calama", amount: 850000, status: "Pending", dte: null },
  ]);
  const [processingId, setProcessingId] = useState<number | null>(null);

  // Mock Data for analysis
  const routeData = [
    { id: "R-101", route: "Stgo - Valpo", driver: "Carlos Mendoza", revenue: 450000, cost: 280000, margin: 37 },
    { id: "R-102", route: "Stgo - Concepción", driver: "Ana Silva", revenue: 1200000, cost: 650000, margin: 45 },
    { id: "R-103", route: "Puerto Montt - Osorno", driver: "Jorge O'Ryan", revenue: 180000, cost: 160000, margin: 11 },
    { id: "R-104", route: "Antofagasta - Calama", driver: "Luis Toro", revenue: 850000, cost: 400000, margin: 52 },
  ];

  const handleGenerateReport = async () => {
    setLoading(true);
    const data = await analyzeFinancials(routeData);
    setReport(data);
    setLoading(false);
  };

  const handleGenerateDTE = (id: number) => {
      setProcessingId(id);
      setTimeout(() => {
          setInvoices(prev => prev.map(inv => 
              inv.id === id ? { ...inv, status: "DTE Generated", dte: `F-${Math.floor(Math.random() * 10000)}` } : inv
          ));
          setProcessingId(null);
      }, 2000);
  };

  return (
    <div className="min-h-screen pt-24 px-4 sm:px-6 lg:px-8 pb-10 bg-dark-950 text-slate-200">
      <div className="max-w-7xl mx-auto animate-fade-in">
        
        {/* Tabs */}
        <div className="flex justify-center mb-8">
            <div className="bg-white/5 p-1 rounded-xl border border-white/10 flex gap-1">
                <button 
                    onClick={() => setActiveTab('profit')}
                    className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all flex items-center gap-2 ${activeTab === 'profit' ? 'bg-brand-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                >
                    <PieChart className="w-4 h-4" /> Rentabilidad
                </button>
                <button 
                    onClick={() => setActiveTab('invoicing')}
                    className={`px-6 py-2.5 rounded-lg text-sm font-bold transition-all flex items-center gap-2 ${activeTab === 'invoicing' ? 'bg-brand-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
                >
                    <FileText className="w-4 h-4" /> Facturación SII
                </button>
            </div>
        </div>

        {activeTab === 'profit' ? (
            // --- PROFITABILITY VIEW ---
            <>
                <div className="flex flex-col md:flex-row justify-between items-end mb-10">
                <div>
                    <h2 className="text-3xl font-bold text-white mb-2">Análisis de Rentabilidad</h2>
                    <p className="text-slate-500">Inteligencia financiera para maximizar márgenes operativos.</p>
                </div>
                <button 
                    onClick={handleGenerateReport}
                    disabled={loading}
                    className="px-6 py-3 bg-white text-black hover:bg-slate-200 font-bold rounded-xl transition-all flex items-center gap-2 shadow-[0_0_20px_rgba(255,255,255,0.1)] disabled:opacity-50"
                >
                    {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Zap className="w-5 h-5 text-brand-600" />}
                    {loading ? 'Analizando Datos...' : 'Generar Reporte IA'}
                </button>
                </div>

                {/* Top Cards generated by AI */}
                {report && (
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 animate-slide-up">
                        <div className="bg-gradient-to-br from-emerald-900/50 to-dark-900 border border-emerald-500/30 p-6 rounded-2xl relative overflow-hidden">
                            <div className="absolute -right-4 -top-4 w-24 h-24 bg-emerald-500/20 rounded-full blur-xl"></div>
                            <h3 className="text-emerald-400 text-xs font-bold uppercase tracking-wider mb-2">Top Performer</h3>
                            <div className="flex items-center gap-3">
                                <Award className="w-8 h-8 text-white" />
                                <div>
                                    <p className="text-2xl font-bold text-white">{report.topDriver}</p>
                                    <p className="text-xs text-slate-400">Conductor Más Rentable</p>
                                </div>
                            </div>
                        </div>

                        <div className="bg-gradient-to-br from-blue-900/50 to-dark-900 border border-blue-500/30 p-6 rounded-2xl relative overflow-hidden">
                            <div className="absolute -right-4 -top-4 w-24 h-24 bg-blue-500/20 rounded-full blur-xl"></div>
                            <h3 className="text-blue-400 text-xs font-bold uppercase tracking-wider mb-2">Ruta Dorada</h3>
                            <div className="flex items-center gap-3">
                                <MapPin className="w-8 h-8 text-white" />
                                <div>
                                    <p className="text-xl font-bold text-white leading-tight">{report.mostProfitableRoute}</p>
                                    <p className="text-xs text-slate-400">Mayor Margen Registrado</p>
                                </div>
                            </div>
                        </div>

                        <div className="bg-gradient-to-br from-purple-900/50 to-dark-900 border border-purple-500/30 p-6 rounded-2xl relative overflow-hidden">
                            <h3 className="text-purple-400 text-xs font-bold uppercase tracking-wider mb-2">Oportunidad de Ahorro</h3>
                            <p className="text-white font-medium text-sm leading-relaxed">{report.costSavingOpportunity}</p>
                        </div>
                    </div>
                )}

                {/* Main Data Table */}
                <div className="glass-panel border border-white/5 rounded-2xl overflow-hidden animate-slide-up" style={{ animationDelay: '0.1s' }}>
                    <div className="p-6 border-b border-white/5 flex justify-between items-center">
                        <h3 className="font-bold text-white">Desglose por Ruta</h3>
                        <span className="text-xs text-slate-500 font-mono">DATOS ULTIMOS 30 DIAS</span>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left">
                            <thead>
                                <tr className="bg-white/5 text-xs uppercase text-slate-400 font-semibold">
                                    <th className="p-4">Ruta</th>
                                    <th className="p-4">Conductor</th>
                                    <th className="p-4 text-right">Ingresos</th>
                                    <th className="p-4 text-right">Costos</th>
                                    <th className="p-4 text-right">Margen</th>
                                    <th className="p-4">Estado</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-white/5">
                                {routeData.map((r) => (
                                    <tr key={r.id} className="hover:bg-white/5 transition-colors">
                                        <td className="p-4 text-white font-medium">{r.route}</td>
                                        <td className="p-4 text-slate-400">{r.driver}</td>
                                        <td className="p-4 text-right text-slate-300">${r.revenue.toLocaleString()}</td>
                                        <td className="p-4 text-right text-slate-400">${r.cost.toLocaleString()}</td>
                                        <td className="p-4 text-right">
                                            <span className={`font-bold ${r.margin > 40 ? 'text-green-400' : r.margin < 20 ? 'text-red-400' : 'text-yellow-400'}`}>
                                                {r.margin}%
                                            </span>
                                        </td>
                                        <td className="p-4">
                                            {r.margin > 40 ? (
                                                <span className="px-2 py-1 bg-green-500/10 text-green-400 text-xs rounded font-bold border border-green-500/20">Optimo</span>
                                            ) : r.margin < 20 ? (
                                                <span className="px-2 py-1 bg-red-500/10 text-red-400 text-xs rounded font-bold border border-red-500/20">Revisar</span>
                                            ) : (
                                                <span className="px-2 py-1 bg-slate-800 text-slate-400 text-xs rounded border border-slate-700">Normal</span>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </>
        ) : (
            // --- INVOICING VIEW ---
            <div className="animate-slide-up">
                 <div className="flex justify-between items-center mb-8">
                    <div>
                        <h2 className="text-3xl font-bold text-white mb-2 flex items-center gap-2">
                            <UploadCloud className="w-8 h-8 text-blue-500" /> Portal SII
                        </h2>
                        <p className="text-slate-500">Emisión automática de Documentos Tributarios Electrónicos.</p>
                    </div>
                    <div className="text-right">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-900/30 border border-green-500/30">
                            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                            <span className="text-xs font-bold text-green-400">CONEXION SII ESTABLE</span>
                        </div>
                    </div>
                 </div>

                 <div className="glass-panel border border-white/5 rounded-2xl overflow-hidden">
                    <div className="p-6 border-b border-white/5 bg-slate-900/50">
                        <h3 className="text-lg font-bold text-white">Servicios Pendientes de Facturación</h3>
                    </div>
                    <table className="w-full text-left">
                        <thead className="bg-white/5 text-xs uppercase text-slate-400">
                            <tr>
                                <th className="p-6">Cliente</th>
                                <th className="p-6">Servicio / Ruta</th>
                                <th className="p-6 text-right">Monto Neto</th>
                                <th className="p-6 text-right">Estado DTE</th>
                                <th className="p-6 text-right">Acción</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-white/5">
                            {invoices.map(inv => (
                                <tr key={inv.id} className="group hover:bg-white/5 transition-colors">
                                    <td className="p-6 font-medium text-white">{inv.client}</td>
                                    <td className="p-6 text-slate-400">{inv.route}</td>
                                    <td className="p-6 text-right font-mono text-lg text-slate-200">${inv.amount.toLocaleString()}</td>
                                    <td className="p-6 text-right">
                                        {inv.status === 'DTE Generated' ? (
                                            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20 text-xs font-bold">
                                                <CheckCircle2 className="w-3 h-3" /> Aceptado {inv.dte}
                                            </span>
                                        ) : (
                                            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-slate-800 text-slate-400 border border-slate-700 text-xs font-bold">
                                                Pendiente
                                            </span>
                                        )}
                                    </td>
                                    <td className="p-6 text-right">
                                        {inv.status === 'Pending' ? (
                                            <button 
                                                onClick={() => handleGenerateDTE(inv.id)}
                                                disabled={processingId === inv.id}
                                                className="px-4 py-2 bg-brand-600 hover:bg-brand-500 text-white text-xs font-bold rounded-lg transition-all flex items-center gap-2 ml-auto disabled:opacity-50"
                                            >
                                                {processingId === inv.id ? <Loader2 className="w-3 h-3 animate-spin" /> : <UploadCloud className="w-3 h-3" />}
                                                {processingId === inv.id ? 'Enviando...' : 'Emitir Factura'}
                                            </button>
                                        ) : (
                                            <button className="px-4 py-2 bg-white/5 hover:bg-white/10 text-slate-300 text-xs font-bold rounded-lg transition-all flex items-center gap-2 ml-auto border border-white/10">
                                                <Printer className="w-3 h-3" /> PDF
                                            </button>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                 </div>
            </div>
        )}

      </div>
    </div>
  );
};

export default Financials;
